name: 'Gitbook Action Build'
on:
  watch:
    types: started
  push:
    branches:
      - main  # trigger branch
  workflow_dispatch:
    inputs:
      name:
        description: '备注'
        required: true
        default: 'Mona the Octocat'
jobs:
   bump:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: tool3/docsify-action@master
      with:      
        github_token: ${{ secrets.PERSONAL_TOKEN }}  
